"""Playwright project bootstrap planning without executing Playwright."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from webapp_debug_skill.cli import CliResult, Issue, emit_result
from webapp_debug_skill.errors import (
    EXIT_ARGUMENT_OR_SCHEMA,
    EXIT_EXTERNAL_FAILURE,
    EXIT_OK,
    EXIT_POLICY_BLOCKED,
    EXIT_UNEXPECTED,
)
from webapp_debug_skill.inventory_model import dumps_snapshot
from webapp_debug_skill.redaction import secret_findings

MANIFEST_SCHEMA_VERSION = 1
GENERATED_MARKER = "@generated by webapp-debug"
DEFAULT_PROJECT_DIR = Path("tests/e2e")
DEFAULT_TEMPLATE = Path("skills/webapp-debug/assets/playwright.config.example.ts")
MANIFEST_NAME = "webapp-debug.generated-manifest.json"
LOCKFILE_MANAGERS = {
    "package-lock.json": "npm",
    "npm-shrinkwrap.json": "npm",
    "pnpm-lock.yaml": "pnpm",
    "yarn.lock": "yarn",
}
IGNORED_DIRS = {".git", "node_modules", "vendor", ".webapp-debug", "__pycache__"}


class PlaywrightProjectError(RuntimeError):
    """Safe Playwright bootstrap error."""

    def __init__(
        self,
        code: str,
        path: str = "playwright_project",
        reason: str = "FAILED",
        *,
        exit_code: int = EXIT_POLICY_BLOCKED,
    ) -> None:
        safe_code = "PLAYWRIGHT_BOOTSTRAP_FAILED" if secret_findings(code) else code
        super().__init__(safe_code)
        self.code = safe_code
        self.path = "playwright_project" if secret_findings(path) else path
        self.reason = "FAILED" if secret_findings(reason) else reason
        self.exit_code = exit_code


@dataclass(frozen=True)
class PlannedFile:
    """One file planned for generated Playwright bootstrap."""

    relative_path: str
    content: bytes
    marker_required: bool = True
    metadata: Mapping[str, Any] = field(default_factory=dict)

    @property
    def checksum(self) -> str:
        """Return sha256 checksum for planned content."""

        return sha256_bytes(self.content)

    @property
    def size(self) -> int:
        """Return content size in bytes."""

        return len(self.content)


@dataclass(frozen=True)
class FileDecision:
    """Safe decision for one planned file."""

    path: str
    action: str
    checksum: str
    size: int

    def to_dict(self) -> dict[str, Any]:
        """Return safe JSON details."""

        return {
            "path": self.path,
            "action": self.action,
            "checksum": self.checksum,
            "size": self.size,
        }


@dataclass(frozen=True)
class BootstrapPlan:
    """A fully validated bootstrap plan."""

    root: Path
    project_dir: Path
    package_manager: str
    files: tuple[PlannedFile, ...]
    decisions: tuple[FileDecision, ...]
    manifest: dict[str, Any]

    def to_safe_dict(self, *, dry_run: bool) -> dict[str, Any]:
        """Return safe CLI data."""

        return {
            "dry_run": dry_run,
            "project_dir": safe_relative_path(self.root, self.project_dir),
            "package_manager": self.package_manager,
            "planned_file_count": len(self.files),
            "create_count": sum(1 for item in self.decisions if item.action == "CREATE"),
            "update_count": sum(1 for item in self.decisions if item.action == "UPDATE"),
            "unchanged_count": sum(1 for item in self.decisions if item.action == "UNCHANGED"),
            "files": [decision.to_dict() for decision in self.decisions],
        }


def build_parser() -> argparse.ArgumentParser:
    """Build bootstrap_playwright_project parser."""

    parser = argparse.ArgumentParser(
        description="Plan or write a generated Playwright project skeleton."
    )
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--project-dir", type=Path, default=DEFAULT_PROJECT_DIR)
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run bootstrap_playwright_project CLI."""

    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        result = run(args)
    except PlaywrightProjectError as exc:
        result = CliResult(
            ok=False,
            code=exc.code,
            message="Playwright project bootstrap failed.",
            details=[Issue(exc.path, exc.reason)],
        )
        emit_result(result, args.format)
        return exc.exit_code
    except Exception:
        result = CliResult(
            ok=False,
            code="PLAYWRIGHT_BOOTSTRAP_UNEXPECTED",
            message="Unexpected Playwright project bootstrap failure.",
            details=[Issue("playwright_project", "UNEXPECTED")],
        )
        emit_result(result, args.format)
        return EXIT_UNEXPECTED
    emit_result(result, args.format)
    return EXIT_OK if result.ok else EXIT_POLICY_BLOCKED


def run(args: argparse.Namespace) -> CliResult:
    """Plan and optionally write a generated Playwright project skeleton."""

    root = resolve_root(args.root)
    project_dir = resolve_project_dir(root, args.project_dir)
    template_path = resolve_template(args.template)
    package_manager = detect_package_manager(root)
    files = planned_files(root, project_dir, template_path, package_manager)
    plan = validate_bootstrap_plan(
        root,
        project_dir,
        package_manager=package_manager,
        files=files,
    )
    if not args.dry_run:
        write_bootstrap_plan(plan)
    data = plan.to_safe_dict(dry_run=args.dry_run)
    return CliResult(
        ok=True,
        code="PLAYWRIGHT_BOOTSTRAP_PLAN" if args.dry_run else "PLAYWRIGHT_BOOTSTRAP_OK",
        message=(
            "Playwright project bootstrap plan generated."
            if args.dry_run
            else "Playwright project skeleton written."
        ),
        details=[],
        data=data,
    )


def resolve_root(path: Path) -> Path:
    """Resolve and validate repository root path."""

    try:
        root = path.expanduser().resolve(strict=True)
    except OSError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_ROOT_INVALID",
            "root",
            "MISSING",
            exit_code=EXIT_ARGUMENT_OR_SCHEMA,
        ) from None
    if not root.is_dir():
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_ROOT_INVALID",
            "root",
            "NOT_DIRECTORY",
            exit_code=EXIT_ARGUMENT_OR_SCHEMA,
        )
    return root


def resolve_project_dir(root: Path, value: Path) -> Path:
    """Resolve project dir below root without allowing escape."""

    if secret_findings(value.as_posix()):
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_PROJECT_DIR_UNSAFE",
            "project_dir",
            "SECRET_DETECTED",
        )
    if value.is_absolute():
        candidate = value.expanduser()
    else:
        candidate = root / value
    project_dir = Path(os.path.normpath(os.fspath(candidate)))
    ensure_within_root(root, project_dir, "project_dir")
    ensure_no_symlink_path(root, project_dir)
    if any(part in {".webapp-debug", "node_modules", "vendor"} for part in project_dir.parts):
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_PROJECT_DIR_UNSAFE",
            "project_dir",
            "FORBIDDEN_DIRECTORY",
        )
    return project_dir


def resolve_template(path: Path) -> Path:
    """Resolve template path and validate it is a regular file."""

    try:
        template = path.expanduser().resolve(strict=True)
    except OSError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_TEMPLATE_INVALID",
            "template",
            "MISSING",
            exit_code=EXIT_ARGUMENT_OR_SCHEMA,
        ) from None
    if not template.is_file():
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_TEMPLATE_INVALID",
            "template",
            "NOT_FILE",
            exit_code=EXIT_ARGUMENT_OR_SCHEMA,
        )
    return template


def detect_package_manager(root: Path) -> str:
    """Detect a single package-manager lock format without executing tooling."""

    lockfiles = find_lockfiles(root)
    managers = {LOCKFILE_MANAGERS[path.name] for path in lockfiles}
    if len(managers) > 1:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_LOCKFILE_CONFLICT",
            "lockfiles",
            "MULTIPLE_LOCK_FORMATS",
        )
    if managers:
        return sorted(managers)[0]
    return "npm"


def find_lockfiles(root: Path) -> tuple[Path, ...]:
    """Return tracked package lock-like files under root, ignoring dependency dirs."""

    result: list[Path] = []
    for current_root, dirs, files in os.walk(root):
        dirs[:] = [item for item in dirs if item not in IGNORED_DIRS]
        for file_name in files:
            if file_name in LOCKFILE_MANAGERS:
                result.append(Path(current_root) / file_name)
    return tuple(sorted(result))


def planned_files(
    root: Path,
    project_dir: Path,
    template_path: Path,
    package_manager: str,
) -> tuple[PlannedFile, ...]:
    """Build deterministic generated skeleton files."""

    config_template = read_text(template_path, "template")
    project_relative = safe_relative_path(root, project_dir)
    package_json = {
        "private": True,
        "name": "webapp-debug-e2e",
        "version": "0.0.0",
        "type": "module",
        "scripts": {
            "test": "playwright test --config=playwright.config.ts",
            "test:headed": "playwright test --headed --config=playwright.config.ts",
        },
        "devDependencies": {"@playwright/test": "^1.45.0"},
        "webappDebug": {
            "generated": True,
            "generator": "webapp-debug",
            "projectDir": project_relative,
            "packageManager": package_manager,
        },
    }
    return (
        PlannedFile(
            relative_path=relative_file(root, project_dir / "package.json"),
            content=(
                json.dumps(package_json, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
            ).encode("utf-8"),
            marker_required=False,
        ),
        PlannedFile(
            relative_path=relative_file(root, project_dir / "playwright.config.ts"),
            content=(
                f"// {GENERATED_MARKER}\n"
                "// Do not edit directly; rerun bootstrap_playwright_project.py.\n"
                f"{config_template}"
            ).encode("utf-8"),
        ),
        PlannedFile(
            relative_path=relative_file(root, project_dir / "generated/.gitkeep"),
            content=generated_note("Generated Scenario specs will be written here in Phase 8B."),
        ),
        PlannedFile(
            relative_path=relative_file(root, project_dir / "fixtures/.gitkeep"),
            content=generated_note("Generated Playwright fixtures will be written here."),
        ),
        PlannedFile(
            relative_path=relative_file(root, project_dir / "pages/index.ts"),
            content=(
                f"// {GENERATED_MARKER}\n"
                "// Page object exports will be generated in a later phase.\n"
                "export {};\n"
            ).encode("utf-8"),
        ),
    )


def generated_note(message: str) -> bytes:
    """Return generated text file content."""

    return f"# {GENERATED_MARKER}\n{message}\n".encode("utf-8")


def validate_bootstrap_plan(
    root: Path,
    project_dir: Path,
    *,
    package_manager: str,
    files: Sequence[PlannedFile],
) -> BootstrapPlan:
    """Validate planned generated files and ownership before writes."""

    manifest_path = project_dir / MANIFEST_NAME
    existing_manifest = read_existing_manifest(manifest_path)
    decisions: list[FileDecision] = []
    manifest = build_manifest(root, project_dir, package_manager, files)
    all_files = (*files, manifest_file(root, manifest_path, manifest))
    for planned in all_files:
        if secret_findings(planned.content.decode("utf-8", errors="replace")):
            raise PlaywrightProjectError(
                "PLAYWRIGHT_BOOTSTRAP_CONTENT_UNSAFE",
                planned.relative_path,
                "SECRET_DETECTED",
            )
        target = root / planned.relative_path
        ensure_within_root(root, target, planned.relative_path)
        ensure_no_symlink_path(root, target)
        action = validate_target_file(
            target,
            planned,
            manifest=existing_manifest,
            manifest_path=manifest_path,
        )
        decisions.append(
            FileDecision(
                path=planned.relative_path,
                action=action,
                checksum=planned.checksum,
                size=planned.size,
            )
        )
    return BootstrapPlan(
        root=root,
        project_dir=project_dir,
        package_manager=package_manager,
        files=all_files,
        decisions=tuple(decisions),
        manifest=manifest,
    )


def read_existing_manifest(path: Path) -> dict[str, Any] | None:
    """Read an existing generated manifest if present."""

    if not path.exists():
        return None
    if path.is_symlink() or not path.is_file():
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_UNSAFE",
            MANIFEST_NAME,
            "NOT_REGULAR_FILE",
        )
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_INVALID",
            MANIFEST_NAME,
            "JSON_INVALID",
        ) from None
    except OSError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_READ_FAILED",
            MANIFEST_NAME,
            "READ_FAILED",
            exit_code=EXIT_EXTERNAL_FAILURE,
        ) from None
    if not isinstance(data, dict) or data.get("schema_version") != MANIFEST_SCHEMA_VERSION:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_INVALID",
            MANIFEST_NAME,
            "SCHEMA_INVALID",
        )
    files = data.get("files")
    if not isinstance(files, list) or not all(isinstance(item, dict) for item in files):
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_INVALID",
            MANIFEST_NAME,
            "FILES_INVALID",
        )
    return data


def build_manifest(
    root: Path,
    project_dir: Path,
    package_manager: str,
    files: Sequence[PlannedFile],
) -> dict[str, Any]:
    """Build deterministic generated manifest payload."""

    return {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "generator": "webapp-debug",
        "project_dir": safe_relative_path(root, project_dir),
        "package_manager": package_manager,
        "files": [
            {
                "path": item.relative_path,
                "sha256": item.checksum,
                "size": item.size,
                "generated_marker_required": item.marker_required,
            }
            | ({"metadata": dict(item.metadata)} if item.metadata else {})
            for item in sorted(files, key=lambda value: value.relative_path)
        ],
    }


def manifest_file(root: Path, manifest_path: Path, manifest: Mapping[str, Any]) -> PlannedFile:
    """Return the manifest as a planned file."""

    return PlannedFile(
        relative_path=relative_file(root, manifest_path),
        content=dumps_snapshot(manifest),
        marker_required=False,
    )


def validate_target_file(
    target: Path,
    planned: PlannedFile,
    *,
    manifest: Mapping[str, Any] | None,
    manifest_path: Path,
) -> str:
    """Return CREATE/UPDATE/UNCHANGED or raise for unsafe overwrite."""

    if not target.exists():
        return "CREATE"
    if target.is_symlink() or not target.is_file():
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_TARGET_UNSAFE",
            planned.relative_path,
            "NOT_REGULAR_FILE",
        )
    current = read_bytes(target, planned.relative_path)
    if current == planned.content:
        return "UNCHANGED"
    if target == manifest_path:
        if manifest is None:
            raise PlaywrightProjectError(
                "PLAYWRIGHT_BOOTSTRAP_MANIFEST_INVALID",
                planned.relative_path,
                "UNVERIFIED_EXISTING_MANIFEST",
            )
        return "UPDATE"
    if manifest is None:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_REQUIRED",
            planned.relative_path,
            "EXISTING_FILE_UNOWNED",
        )
    entry = manifest_entry(manifest, planned.relative_path)
    if entry is None:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_MISMATCH",
            planned.relative_path,
            "ENTRY_MISSING",
        )
    if entry.get("sha256") != sha256_bytes(current):
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_MISMATCH",
            planned.relative_path,
            "CHECKSUM_MISMATCH",
        )
    marker_required = bool(entry.get("generated_marker_required", True))
    if marker_required and GENERATED_MARKER not in current.decode("utf-8", errors="replace"):
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_MANIFEST_MISMATCH",
            planned.relative_path,
            "GENERATED_MARKER_MISSING",
        )
    return "UPDATE"


def manifest_entry(manifest: Mapping[str, Any], relative_path: str) -> Mapping[str, Any] | None:
    """Return a manifest entry by relative path."""

    files = manifest.get("files", [])
    if not isinstance(files, list):
        return None
    for item in files:
        if isinstance(item, Mapping) and item.get("path") == relative_path:
            return item
    return None


def write_bootstrap_plan(plan: BootstrapPlan) -> None:
    """Write all generated files using atomic replace."""

    for planned in plan.files:
        target = plan.root / planned.relative_path
        atomic_write(target, planned.content)


def atomic_write(path: Path, content: bytes) -> None:
    """Atomically write one generated file."""

    tmp_path: Path | None = None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
        tmp_path = Path(tmp_name)
        with os.fdopen(fd, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
        tmp_path = None
        fsync_dir(path.parent)
    except OSError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_WRITE_FAILED",
            safe_path(path),
            "WRITE_FAILED",
            exit_code=EXIT_EXTERNAL_FAILURE,
        ) from None
    finally:
        if tmp_path is not None:
            tmp_path.unlink(missing_ok=True)


def ensure_no_symlink_path(root: Path, target: Path) -> None:
    """Reject symlink components from root to target."""

    current = root
    for part in target.relative_to(root).parts:
        current = current / part
        try:
            info = current.lstat()
        except OSError:
            continue
        if stat.S_ISLNK(info.st_mode):
            raise PlaywrightProjectError(
                "PLAYWRIGHT_BOOTSTRAP_TARGET_UNSAFE",
                safe_relative_path(root, current),
                "SYMLINK_REJECTED",
            )


def ensure_within_root(root: Path, path: Path, label: str) -> None:
    """Ensure a path is inside the root."""

    try:
        path.relative_to(root)
    except ValueError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_PATH_UNSAFE",
            label,
            "OUTSIDE_ROOT",
        ) from None


def read_text(path: Path, label: str) -> str:
    """Read a UTF-8 text file safely."""

    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_TEMPLATE_INVALID",
            label,
            "UTF8_REQUIRED",
            exit_code=EXIT_ARGUMENT_OR_SCHEMA,
        ) from None
    except OSError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_READ_FAILED",
            label,
            "READ_FAILED",
            exit_code=EXIT_EXTERNAL_FAILURE,
        ) from None


def read_bytes(path: Path, label: str) -> bytes:
    """Read bytes safely."""

    try:
        return path.read_bytes()
    except OSError:
        raise PlaywrightProjectError(
            "PLAYWRIGHT_BOOTSTRAP_READ_FAILED",
            label,
            "READ_FAILED",
            exit_code=EXIT_EXTERNAL_FAILURE,
        ) from None


def sha256_bytes(content: bytes) -> str:
    """Return sha256 digest string."""

    return "sha256:" + hashlib.sha256(content).hexdigest()


def relative_file(root: Path, path: Path) -> str:
    """Return a POSIX-style path relative to root."""

    return path.relative_to(root).as_posix()


def safe_relative_path(root: Path, path: Path) -> str:
    """Return safe relative path text."""

    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return "<outside-root>"


def safe_path(path: Path) -> str:
    """Return basename-only diagnostic path."""

    return path.name or "path"


def fsync_dir(directory: Path) -> None:
    """Fsync a directory where supported."""

    try:
        fd = os.open(directory, os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    finally:
        os.close(fd)
